print " _________"
print " \_     _/"
print "   \   /"
print "    | |"
print "   /   \"
print "  /     \"
print " |       |"
print "/---------\"
print "| \-/ \-/ |"
print "\---------/"
print " \_______/"
sleep